spring:
  application:
    name: ai_code_helper
server:
  port: 8081
  servlet:
    context-path: /api
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-turbo
        api-key: ${AI_DASHSCOPE_API_KEY:sk-请填入你的百炼密钥}
      embedding-model:
        model-name: text-embedding-v4
        api-key: ${AI_DASHSCOPE_API_KEY:sk-请填入你的百炼密钥}
      streaming-chat-model:
        model-name: qwen-turbo
        api-key: ${AI_DASHSCOPE_API_KEY:sk-请填入你的百炼密钥}
big model:
  api-key: ${BIGMODEL_API_KEY:sk-你的大模型API-KEY}